server:
  port: 8085
spring:
  application:
    name: streams
    devtools:
      restart:
        enabled: true
  eureka:
    instance:
      instance-id: ${spring:application:name}:${spring:application:instance_id:${random:value}}
  cloud:
    stream:
      bindings:
        statisticProcessor-in-0:
          destination: log-topic
        statisticProcessor-out-0:
          destination: statistic-topic
        alertsProcessor-in-0:
          destination: statistic-topic
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              processing:
                guarantee: exactly_once
              default:
                timestamp:
                  extractor: org.united.project.micro.streams.LogTimestampExtractor
            functions:
              averageProcessor:
                applicationId: statisticProcessor-v1
              alertsProcessor:
                applicationId: alertsProcessor-v1
            application-id: streams
    function:
      definition: statisticProcessor;alertsProcessor;

# logging:
#  level:
#    org.apache.kafka.streams: DEBUG